src/Entity/Cart.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CartRepository")
 */
class Cart
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="cart")
     */
    private $user;

    /**
     * * @ORM\ManyToOne(targetEntity="App\Entity\Products", inversedBy="cart")
     */
    private $product;

    /**
     * @ORM\Column(type="integer")
     */
    private $total_price;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getProduct(): ?Products
    {
        return $this->product;
    }

    public function setProduct(?Products $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getTotalPrice(): ?int
    {
        return $this->total_price;
    }

    public function setTotalPrice(int $total_price): self
    {
        $this->total_price = $total_price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Controller/Frontend/HomeController.php
<?php

namespace App\Controller\Frontend;

use App\Repository\ProductsRepository;
use App\Services\ProductsService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    protected $productsRepository;

    protected $productsService;

    public function __construct(ProductsRepository $productsRepository,ProductsService $productsService)
    {
        $this->productsRepository = $productsRepository;
        $this->productsService = $productsService;
    }

    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        $products = $this->productsService->getProducts();

        return $this->render('home/index.html.twig', [
            'products' => $products
        ]);
    }

    /**
     * @Route("/product/detail/{product_id}", name="product.detail")
     */
    public function detail($product_id)
    {

    }
}

templates/home/cart.html.twig
{% extends('layouts/home.html.twig') %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>Ürün Resmi</th>
                            <th>Ürün Adı</th>
                            <th>Adet</th>
                            <th>Fiyat</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% set total = 0 %}
                        {% for item in cart %}
                            <tr>
                                <td>
                                    <img width="100" src="{{ asset('uploads/products/' ~ item.product.image) }}"
                                         alt="">
                                </td>
                                <td>{{ item.product.title }}</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.totalPrice }}</td>
                            </tr>
                            {% set total = total + item.totalPrice  %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div style="float: right">
                Toplam : {{ total }} TL
                <a href="{{ path('user.order.create') }}" class="btn btn-success">
                    Sipariş Ver
                </a>
            </div>

        </div>
    </div>
{% endblock %}

templates/home/index.html.twig
{% extends('layouts/home.html.twig') %}

{% block body %}
    <div class="row">
        {% for product in products %}
            <div class="col-md-4">
                <div class="bbb_deals">
                    <div class="bbb_deals_slider_container">
                        <div class=" bbb_deals_item">
                            <a href="">
                                <div class="bbb_deals_image"><img src="{{ asset('uploads/products/' ~ product.image) }}"
                                                                  alt=""></div>
                                <div class="bbb_deals_content">
                                    <div class="bbb_deals_info_line d-flex flex-row justify-content-start">
                                        <div class="bbb_deals_item_name">{{ product.title }}</div>
                                        <div class="bbb_deals_item_price ml-auto">{{ product.price }} TL</div>
                                    </div>
                                    <div class="available">
                                        <div class="available_line d-flex flex-row justify-content-start">
                                            <div class="available_title">Stokta <span>{{ product.stock }}</span></div>
                                        </div>
                                        <div class="available_bar"><span style="width:17%"></span></div>
                                        <a href="{{ path('user.cart.add_product',{product_id : product.id}) }}">
                                            <div class="available_title_inspect">
                                                Sepete Ekle
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/home/order.html.twig
{% extends('layouts/home.html.twig') %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Sipariş Ver</h3>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <!-- general form elements disabled -->
            <div class="card card-warning">
                <!-- /.card-header -->
                <div class="card-body">
                    <form method="post" action="{{ path('user.order.store') }}" enctype="multipart/form-data">
                        <div class="row">
                            <div class="col-sm-12">
                                <!-- textarea -->
                                <div class="form-group">
                                    <label>Adres</label>
                                    <textarea class="form-control" rows="3" placeholder="Sipariş Adresi"
                                              name="address"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-success">Sipariş Ver</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}